schemas = ["./schemas/identity.schema.json"]

[module]
name = "AWS Region Module"
url = "https://github.com/rescile/aws-region-module"
version = "0.0.1"
description = "Creates and configures an AWS region as a managed infrastructure target for subsequent resource deployments."
rescile_version = ">=0.1.193"

# List of other modules this module depends on.
[dependencies]
