[dns]
[dns.route53_private_zone]
domain_name = "my.salesforce.com"
comment = "Intercepts Salesforce traffic for private routing"

[[dns.route53_private_zone.records]]
name = "your-org-instance"
type = "A"
alias_target = "vpce-xxxxxxxxxxxx-xxxxx.vpce.us-east-1.vpce.amazonaws.com"

[governance]
[governance.vpc_flow_logs]
traffic_type = "ALL"
log_destination_type = "cloudwatch-logs"
retention_in_days = 90
