origin_resource = "region"

[[create_resource]]
create_from = { property = "availability_zone" }
relation_type = "CONNECTED_TO"
name = "{% for z in origin_resource.availability_zones %}{{- origin_resource.name | lower -}}{{- z | lower -}}{% endfor %}"
[create_resource.properties]
function = "{{ origin_resource._type }}"
domain_id = "{{- property.value | lower -}}"
description = "AWS's availability zones spread your resources across AZs to achieve high availability. These are geographically separated but close enough for low-latency connections between them, each has independent power, cooling, and networking."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"
