origin_resource = "location"

provider = { "json!" = "provider.json", jmespath = '["Amazon Web Services"]' }
regions = { "json!" = "aws-regions.json"}

[[create_resource]]
resource_type = "region"
relation_type = "DERIVED_FROM"
name = "{{- origin_resource.name -}}"
#name = "{{- regions[Zurich].aws_region_id -}}"
[create_resource.properties]
function = "{{- origin_resource.function -}}"
provider = "{{- provider -}}"
availability_zone = ["a","b"]
api    = "https://service-code.region-code.amazonaws.com"
kms    = "{{- provider[0].name | lower -}}-{{- origin_resource.code | lower -}}-vault"
router = "{{- provider[0].name | lower -}}-{{- origin_resource.code | lower -}}-transit-router"
description = "The region describes a physical, geographical location where data is stored, and applications run, managed by {{ provider[0].name }}."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"
