origin_resource = "region"

[[create_resource]]
create_from = { property = "router" }
relation_type = "CONNECTS_TO"
[create_resource.properties]
function = "connectivity"
region = "{{- origin_resource.name -}}"
ipv6 = false
description = "{{ origin_resource.provider[0].name | upper }}'s  transit router in {{ origin_resource.location[0].name | capitalize }} is a regional network function that analyzes incoming data packets and forwards them toward their intended destination."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"
